### PR TITLE
Fix file info TW 5.1.23-pre

### PR DESCRIPTION
**Pull request by joshuafontany**
Looks like you got the core of the bug-fixes into the release, well done.  This remaining code here does depend on my TW fix-fileInfo.

 One thing I noted is that you require the tiddler to have changed before initiating a save. This may come up false (the tiddler data is the same) but a new file-path could be generated by the filters, requiring a save/delete. 

This is what my core TW patch fixes, and we can wait until it is merged into TW core to implement this in Bob. (I can always keep using my Dev branches of both).

Best,
Joshua F

### CODE REVIEW

**Comment by inmysocks** [comment]
I think I misunderstood what this change does. Is this supposed to add a feature that makes the file system paths filters change all existing tiddlers?

If so I am not sure when this would ever take effect, if the tiddler file has been moved on the filesystem the update is handled by the file system monitor, if a tiddler hasn't been modified in the browser the syncer in the browser has no reason to send a save task. Is that part of the core changes that go along with this? I need to look at that closer.

**Comment by joshuafontany** [comment]
There will be a rare case where the Tiddler itself has not changed, but Save is called and the resulting File Info will have changed. This is SUPER RARE, but exist, for example as a button that deletes a _nonexistant_ field from a tiddler in order to "touch" it (this is how I "unpack" shadowtiddlers). If the FileSystemPath filters have changed, this should move tiddlers to the new location on disk, even though the tiddler data is the same as the copy on the server.

Like I said, corner case "bug/feature" territory, but this was the best logic flow I could find that was not filled with if/then tests.

**Comment by linonetwo** [comment]
When will this be merged? I really want to use this to handle moving files between public github repo and private github repo in my app.

**Comment by joshuafontany** [comment]
Probably until after the fix is merged into the TW core repo. Please comment over there as that has fallen off the active PRs iver there. I might need to refactor that fix also for a recent issue that came up.

**Comment by joshuafontany** [comment]
I will be looking at syncing up Bob's logic with the new TW5.1.23 core filesystem changes in a separate PR.

**Pull request closed without merging**
