### PR TITLE
Fix fileInfo

### PR DESCRIPTION
**Pull request by joshuafontany**
Based on the patch that addresses this in TW core: https://github.com/Jermolene/TiddlyWiki5/pull/4630

You must have that patch installed to test this PR.

This fixes a couple of things. The first was to catch a null value in the FileSystemMonitor.js watch functions that would kick a fatal error every once in a while.

Next, we fix a race condition in MultiWikiAdaptor.js where a brand new tiddler was being saved to disk before being saved into server memory and then pushed to any open clients. This caused all filters in the $:/config/FileSystemPaths that relied on querying tags or fields to fail silently. Calling the Internal Save _first_ fixes that.

I also incorporated the flow from the TW fix-fileInfo patch that tests for custom file extensions filters ($:/config/FileSystemExtensions) and a new path-on-disk every time a tiddler is saved, deleting the old file if necessary.

Testing this against my wiki-in-progress now, but this seems to have unblocked me from using Bob for my latest wiki.

Thanks,
Joshua F

### CODE REVIEW

**Comment by inmysocks** [comment]
I have been trying to track down that race condition for months, thank you. I need to look through all of this so I have a clear idea of the changes before I merge it but all of this looks great.

**Comment by xeor** [comment]
This took away a "create tiddler" loop in the browser console for me, which I suspect is a good thing :)

**Comment by inmysocks** [comment]
I plan on using everything here, but I don't want to merge anything that requires a change to the core so that part is going to wait until the next version of tiddlywiki is released with your changed merged there.
I would like to merge the changes that don't require any core changes. I think that is everything but some of the changes to MultiWikiAdaptor.js.
I can't find a way to merge only specific files, if you can either split this into two pull requests, one that doesn't require core changes and the other with the updates from the next version of tiddlywiki, I can merge the first one now.

If not I am going to try and just manually change the affected files, I am hoping to release a new version of Bob this weekend.

**Comment by joshuafontany** [comment]
Hi @inmysocks 

Wish I had seen this earlier, but work has me slammed this weekend. Looks like you have been importing all the stuff compatible with TW5.1.22 core so far. Awesome! I'll re-factor this PR to just be about the changes for the FileSystemExtensions changes in the TW PR.

If I notice anything else as you incorporate these updates, I'll open a new issue/PR. I'm looking to use Bob to host a few different public projects really soon. Awesome to see this fix going in, and I do want to work with you on the Federation stuff (My RPG wiki edition is going to be killer with that feature). But that project is a few down the list. ;)

Thanks!
Joshua F

**Comment by joshuafontany** [comment]
Closing and re-targeting against master. I actually think you could merge all my changes here without any dependency on the similar changes in the TW core plugins. I want to make 100% sure tho.

**Pull request closed without merging**
